### ISSUE TITLE
Permission denied: '/usr/bin' for ChromeDriver

### ISSUE THREAD

**Issue by ThoEngel** [Paperspace/DinoRunTutorial#7]
I start the code in a virtual environment of python and i get the following error:
How can I fix the permission conflict?

`(ENV) te@te-ThinkPad-T460s:~/Programming/Python/DinoRunTutorial$ python3 Main.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/te/Programming/Python/DinoRunTutorial/ENV/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 372, in <module>
    playGame(observe=False);
  File "Main.py", line 362, in playGame
    game = Game()
  File "Main.py", line 66, in __init__
    self._driver = webdriver.Chrome(executable_path = chrome_driver_path,chrome_options=chrome_options)
  File "/home/te/Programming/Python/DinoRunTutorial/ENV/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/te/Programming/Python/DinoRunTutorial/ENV/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'bin' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

**Comment by ravi72munde** [comment]
This seems to be a problem with your chromium webdriver version. Check this too
https://stackoverflow.com/questions/47148872/webdrivers-executable-may-have-wrong-permissions-please-see-https-sites-goo/52131631

Verify you are correctly passing the driver path as per your os
